#!/bin/bash

# preinstall script for truSTW pkg installers
# v0.2

rm -f /tmp/truSTW.temp 2>/dev/null
pid=$(pgrep -l truSTW | awk '{print $1}')
if [[ "$pid" ]] ; then
	unm=$(scutil <<< "show State:/Users/ConsoleUser" | awk '/Name :/ && ! /loginwindow/ { print $3 }')
	uid=$(id -u "$unm")
	if [[ $uid ]] ; then
		echo -n "$uid" > /tmp/truSTW.temp 2>/dev/null
	else
		echo -n "-" > /tmp/truSTW.temp 2>/dev/null
	fi
	osascript -e 'tell application "truSTW" to quit' 2>/dev/null || killall truSTW 2>/dev/null
	while true
	do
		sleep 1
		! [[ $(pgrep truSTW) ]] && break
	done
else
	echo -n "-" > /tmp/truSTW.temp 2>/dev/null
fi

read -dr '' target_dirs <<"EOF"
/Library/Application Support/truSTW/authorities
/Library/Application Support/truSTW/intermediates
/Library/Application Support/truSTW/identities
/Library/Application Support/truSTW/user
EOF

read -dr '' sub_dirs <<"EOF"
whitelists
graylists
blacklists
EOF

support_dir="/Library/Application Support/truSTW"
if ! [[ -d "$support_dir" ]] ; then
	rm -rf "${support_dir:?}" 2>/dev/null
	while read -r target_dir
	do
		mkdir -p "$target_dir/whitelists" 2>/dev/null
		mkdir "$target_dir/graylists" 2>/dev/null
		mkdir "$target_dir/blacklists" 2>/dev/null
	done < <(echo "$target_dirs" | grep -v "^$")
else
	while read -r target_dir
	do
		if ! [[ -d "$target_dir" ]] ; then
			rm -rf "${target_dir:?}" 2>/dev/null
			mkdir -p "$target_dir/whitelists" 2>/dev/null
			mkdir "$target_dir/graylists" 2>/dev/null
			mkdir "$target_dir/blacklists" 2>/dev/null
		else
			while read -r sub_dir
			do
			if ! [[ -d "$target_dir/$sub_dir" ]] ; then
				rm -rf "${target_dir:?}/$sub_dir" 2>/dev/null
				mkdir "$target_dir/$sub_dir" 2>/dev/null
			fi
			done < <(echo "$sub_dirs" | grep -v "^$")
		fi
	done < <(echo "$target_dirs" | grep -v "^$")
fi
while read -r target_dir
do
	rm -f "${target_dir:?}/whitelists/initial" 2>/dev/null
	rm -f "${target_dir:?}/graylists/initial" 2>/dev/null
	rm -f "${target_dir:?}/blacklists/initial" 2>/dev/null
done < <(echo "$target_dirs" | grep -v -e "^$" -e "/truSTW/user$")
rm -f "${support_dir:?}/user/template.txt" 2>/dev/null

exit 0
